#!/bin/bash

PRIVATE_LOCATION="/var/packages/${SYNOPKG_PKGNAME}/target/package"
START_FILE="./start.sh"
STOP_FILE="./stop.sh"

case $1 in
    start)
        cd ${PRIVATE_LOCATION}
        /bin/sh ${START_FILE}
    ;;
    stop)
        cd ${PRIVATE_LOCATION}
        (/bin/sh ${STOP_FILE} &)
    ;;
    status)
        cd ${PRIVATE_LOCATION}
        ret=$(ps -ef | grep tempature | grep -v 'grep')
        if [ -n "${ret}" ]; then
            exit 0
        else
            exit 1
        fi
    ;;
esac