#!/bin/bash
case "$1" in
    start)
        if [ "${EUID}" -eq 0 ]; then
            sudo -u root synosystemctl start pkguser-unas
        else
            synosystemctl start pkguser-unas
        fi
        ;;
    stop)
        if [ "${EUID}" -eq 0 ]; then
            sudo -u root synosystemctl stop pkguser-unas
        else
            synosystemctl stop pkguser-unas
        fi
        ;;
    status)
        if [ "${EUID}" -eq 0 ]; then
            sudo -u root synosystemctl get-active-status pkguser-unas
        else
            synosystemctl get-active-status pkguser-unas
        fi
        ;;
    log)
        echo ""
        ;;
    *)
        echo "Usage: $0 {start|stop|status}" >&2
        exit 1
        ;;
esac
